/** German UI copy for compliance user activity reports. */
export const userActivityReportCopy = {
    pageTitle: 'Benutzer-Aktivitätsbericht',
    pageIntro:
        'Compliance-Bericht mit Login-, Sitzungs- und Audit-Daten (RKSV). Export als CSV für Behörden oder PDF zur Archivierung.',
    selectUser: 'Benutzer',
    selectUserPlaceholder: 'Benutzer suchen …',
    dateRange: 'Zeitraum',
    actionType: 'Aktionstyp',
    actionTypeAll: 'Alle Aktionen',
    generate: 'Bericht erstellen',
    exportCsv: 'CSV exportieren',
    exportPdf: 'PDF exportieren',
    scheduleReport: 'Bericht planen',
    scheduleTitle: 'Bericht per E-Mail planen',
    scheduleName: 'Name',
    scheduleRecipients: 'Empfänger (E-Mail, kommagetrennt)',
    scheduleWeekly: 'Wöchentlich (Montag 08:00 UTC)',
    scheduleMonthly: 'Monatlich (1., 08:00 UTC)',
    scheduleSuccess: 'Bericht wurde geplant.',
    totalActions: 'Aktionen gesamt',
    totalLogins: 'Anmeldungen',
    failedLogins: 'Fehlgeschlagene Anmeldungen',
    activeSessions: 'Aktive Sitzungen',
    avgSession: 'Ø Sitzungsdauer',
    lastLogin: 'Letzter Login',
    topActiveUsers: 'Aktivste Benutzer (Vergleich)',
    actionBreakdown: 'Aktionsverteilung',
    activityOverTime: 'Aktivität im Zeitverlauf',
    timeline: 'Audit-Zeitleiste (RKSV)',
    noData: 'Bitte Benutzer und Zeitraum wählen und Bericht erstellen.',
    loadError: 'Bericht konnte nicht geladen werden.',
    userCreates: 'Benutzer angelegt',
    userEdits: 'Benutzer bearbeitet',
    payments: 'Zahlungen',
    stornos: 'Stornos',
    refunds: 'Erstattungen',
    exports: 'Exporte',
    hubTitle: 'Berichte',
    hubIntro: 'Compliance- und Betriebsberichte.',
    openUserActivity: 'Benutzer-Aktivität',
};

export const ACTION_TYPE_OPTIONS = [
    { value: '', label: 'Alle' },
    { value: 'USER_LOGIN', label: 'USER_LOGIN' },
    { value: 'PaymentCreated', label: 'PaymentCreated' },
    { value: 'PaymentReversal', label: 'PaymentReversal' },
    { value: 'PaymentRefunded', label: 'PaymentRefunded' },
    { value: 'POS_PAY_OUTCOME', label: 'POS_PAY_OUTCOME' },
    { value: 'USER_UPDATE', label: 'USER_UPDATE' },
];
