// <auto-generated />
using KasseAPI_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KasseAPI_Final.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260520120000_AddMustChangePasswordOnNextLogin")]
partial class AddMustChangePasswordOnNextLogin
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Target model is defined in AppDbContextModelSnapshot (previous migration chain).
    }
}
