// <auto-generated />
using KasseAPI_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KasseAPI_Final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316160000_AddBenefitDailyUsageAndAllowanceCategoryId")]
    partial class AddBenefitDailyUsageAndAllowanceCategoryId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            MigrationDesignerModel.BuildCurrent(modelBuilder);
        }
    }
}