//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("a8f3e1b2-9c4d-4e7f-a1b2-3c4d5e6f7080")]
[assembly: System.Reflection.AssemblyCompanyAttribute("KasseAPI_Final")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+57700807191d83c77a5458e85ef0ec38f3de1842")]
[assembly: System.Reflection.AssemblyProductAttribute("KasseAPI_Final")]
[assembly: System.Reflection.AssemblyTitleAttribute("KasseAPI_Final")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("KasseAPI_Final.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

