export {
  ENVIRONMENT_CONFIG,
  type EnvironmentBadgeColor,
  type EnvironmentBadgeSnapshot,
  type EnvironmentBannerKind,
  type ReleaseStage,
  getEnvironmentBadge,
  getEnvironmentBadgeColor,
  getEnvironmentBadgeText,
  getReleaseStageBannerColor,
  getReleaseStageBannerKind,
  getReleaseStageBannerLabel,
  normalizeReleaseStage,
  readEnvironmentSnapshot,
} from '../../../../shared/constants/environment';
