/**
 * Users module copy – i18n-ready keys (replace values or use with t(key) when i18n is added).
 * Password min length from validation.ts (single source of truth; must match backend Identity).
 */
import { PASSWORD_MIN_LENGTH } from './validation';

export const usersCopy = {
  title: 'Benutzerverwaltung',
  name: 'Name',
  email: 'E-Mail',
  role: 'Rolle',
  branch: 'Standort',
  status: 'Status',
  lastLogin: 'Letzter Login',
  actions: 'Aktionen',
  create: 'Benutzer anlegen',
  edit: 'Bearbeiten',
  view: 'Ansehen',
  deactivate: 'Deaktivieren',
  reactivate: 'Reaktivieren',
  activity: 'Aktivität',
  filterRole: 'Rolle',
  filterStatus: 'Status',
  filterBranch: 'Standort',
  searchPlaceholder: 'Name, E-Mail, Mitarbeiternummer …',
  statusActive: 'Aktiv',
  statusInactive: 'Inaktiv',
  statusAll: 'Alle',
  createUser: 'Benutzer anlegen',
  createRole: 'Rolle anlegen',
  editUser: 'Benutzer bearbeiten',
  deactivateUser: 'Benutzer deaktivieren',
  reactivateUser: 'Benutzer reaktivieren',
  reasonRequired: 'Grund (für Audit erforderlich)',
  reasonPlaceholder: 'z. B. Ausscheiden, Urlaub, …',
  reasonRequiredMessage: 'Bitte einen Grund angeben.',
  confirmDeactivate: 'wird deaktiviert. Fiş/fatura referansları korunur; Konto kann später reaktiviert werden.',
  confirmReactivate: 'wieder aktivieren?',
  okDeactivate: 'Deaktivieren',
  okReactivate: 'Reaktivieren',
  close: 'Schließen',
  save: 'Speichern',
  cancel: 'Abbrechen',
  userName: 'Benutzername',
  password: 'Passwort',
  firstName: 'Vorname',
  lastName: 'Nachname',
  employeeNumber: 'Mitarbeiternummer',
  taxNumber: 'Steuernummer',
  notes: 'Notizen',
  activityTimeline: 'Aktivitätsverlauf',
  activityFor: 'Aktivitätsverlauf für',
  activityTime: 'Zeit',
  action: 'Aktion',
  description: 'Beschreibung',
  emptyList: 'Keine Benutzer gefunden.',
  emptyActivity: 'Keine Aktivität.',
  errorLoad: 'Benutzerliste konnte nicht geladen werden.',
  errorLoadUser: 'Benutzerdaten konnten nicht geladen werden.',
  errorLoadActivity: 'Aktivitätsverlauf konnte nicht geladen werden.',
  errorLoadActivityHint: 'Übrige Benutzerdetails sind weiterhin nutzbar.',
  retry: 'Erneut versuchen',
  successCreate: 'Benutzer angelegt.',
  successUpdate: 'Benutzer aktualisiert.',
  successDeactivate: 'Benutzer deaktiviert.',
  successReactivate: 'Benutzer reaktiviert.',
  errorGeneric: 'Fehler.',
  noPermission: 'Nur Admins (Admin/SuperAdmin) können Benutzer verwalten.',
  accessDenied: 'Sie haben keine Berechtigung, Benutzer anzuzeigen.',
  branchNotAvailable: '—',
  details: 'Details',
  resetPassword: 'Passwort zurücksetzen',
  resetPasswordUser: 'Passwort zurücksetzen',
  newPassword: `Neues Passwort (min. ${PASSWORD_MIN_LENGTH} Zeichen, Groß-/Kleinbuchstaben, Zahl, Sonderzeichen)`,
  successResetPassword: 'Passwort wurde zurückgesetzt. Sitzungen des Benutzers wurden ungültig.',
  errorResetPassword: 'Passwort konnte nicht zurückgesetzt werden.',
  errorResetPasswordUserNotFound: 'Benutzer wurde nicht gefunden.',
  errorResetPasswordForbidden: 'Keine Berechtigung, dieses Passwort zurückzusetzen.',
  sessionExpiredOrUnauthorized: 'Sitzung abgelaufen oder nicht angemeldet. Bitte erneut anmelden.',
  successCreateRole: 'Rolle angelegt.',
  roleName: 'Rollenname',
  roleNameRequired: 'Rollenname erforderlich',
  // Role management (Rollen verwalten)
  manageRoles: 'Rollen verwalten',
  manageRolesDescription: 'Rollen und Berechtigungen verwalten. Änderungen an Berechtigungen wirken sich auf die Menü- und Funktionssichtbarkeit der Benutzer aus.',
  newRole: 'Neue Rolle',
  deleteRole: 'Rolle löschen',
  savePermissions: 'Berechtigungen speichern',
  systemRoleNoDelete: 'Systemrollen können nicht gelöscht werden.',
  roleHasUsers: 'Rolle kann nicht gelöscht werden: mindestens ein Benutzer ist zugewiesen.',
  confirmCloseWithDirty: 'Ungespeicherte Änderungen verwerfen?',
  successPermissionsSaved: 'Berechtigungen gespeichert.',
  successRoleDeleted: 'Rolle gelöscht.',
  errorSavePermissions: 'Berechtigungen konnten nicht gespeichert werden.',
  errorDeleteRole: 'Rolle konnte nicht gelöscht werden.',
  noRoleSelected: 'Rolle auswählen',
  permissionsByGroup: 'Berechtigungen nach Gruppe',
  userCount: (n: number) => (n === 1 ? '1 Benutzer' : `${n} Benutzer`),
  presetLabel: 'Preset anwenden',
  presetPlaceholder: 'Vorlage wählen …',
  // Validierung (zentral; Policy = backend Program.cs Identity)
  validationRequired: 'Pflichtfeld.',
  validationEmail: 'Ungültige E-Mail-Adresse.',
  validationPasswordMin: `Min. ${PASSWORD_MIN_LENGTH} Zeichen.`,
  validationPasswordPolicy: 'Mindestens ein Großbuchstabe, ein Kleinbuchstabe, eine Zahl und ein Sonderzeichen.',
  validationMaxLength: (n: number) => `Max. ${n} Zeichen.`,
  // Reset-Passwort: Sicherheitshinweis (Policy = backend Identity)
  resetPasswordSecurityNote: `Alle Sitzungen des Benutzers werden beendet. Das neue Passwort muss mindestens ${PASSWORD_MIN_LENGTH} Zeichen haben sowie Groß- und Kleinbuchstaben, eine Zahl und ein Sonderzeichen.`,
  // Backend/Identity validation errors (DE) – for display in modal when backend returns 400
  resetPasswordErrorMinLength: 'Das Passwort muss mindestens 8 Zeichen haben.',
  resetPasswordErrorDigit: 'Das Passwort muss mindestens eine Ziffer enthalten.',
  resetPasswordErrorLowercase: 'Das Passwort muss mindestens einen Kleinbuchstaben enthalten.',
  resetPasswordErrorUppercase: 'Das Passwort muss mindestens einen Großbuchstaben enthalten.',
  resetPasswordErrorNonAlphanumeric: 'Das Passwort muss mindestens ein Sonderzeichen enthalten.',
  resetPasswordErrorGeneric: 'Das Passwort erfüllt die Anforderungen nicht.',
} as const;

/** Maps backend/Identity English password error message to German for modal display. */
export function mapBackendPasswordErrorToGerman(backendMessage: string, copy: typeof usersCopy): string {
  const lower = backendMessage.toLowerCase();
  if (lower.includes('at least') && lower.includes('character')) return copy.resetPasswordErrorMinLength;
  if (lower.includes('digit') || lower.includes('number')) return copy.resetPasswordErrorDigit;
  if (lower.includes('lowercase') || lower.includes('lower case')) return copy.resetPasswordErrorLowercase;
  if (lower.includes('uppercase') || lower.includes('upper case')) return copy.resetPasswordErrorUppercase;
  if (lower.includes('non-alphanumeric') || lower.includes('non alphanumeric') || lower.includes('special')) return copy.resetPasswordErrorNonAlphanumeric;
  return copy.resetPasswordErrorGeneric;
}
