/**
 * Users module copy – i18n-ready keys (replace values or use with t(key) when i18n is added).
 */
export const usersCopy = {
  title: 'Benutzerverwaltung',
  name: 'Name',
  email: 'E-Mail',
  role: 'Rolle',
  branch: 'Standort',
  status: 'Status',
  lastLogin: 'Letzter Login',
  actions: 'Aktionen',
  create: 'Benutzer anlegen',
  edit: 'Bearbeiten',
  view: 'Ansehen',
  deactivate: 'Deaktivieren',
  reactivate: 'Reaktivieren',
  activity: 'Aktivität',
  filterRole: 'Rolle',
  filterStatus: 'Status',
  filterBranch: 'Standort',
  searchPlaceholder: 'Name, E-Mail, Mitarbeiternummer …',
  statusActive: 'Aktiv',
  statusInactive: 'Inaktiv',
  statusAll: 'Alle',
  createUser: 'Benutzer anlegen',
  createRole: 'Rolle anlegen',
  editUser: 'Benutzer bearbeiten',
  deactivateUser: 'Benutzer deaktivieren',
  reactivateUser: 'Benutzer reaktivieren',
  reasonRequired: 'Grund (für Audit erforderlich)',
  reasonPlaceholder: 'z. B. Ausscheiden, Urlaub, …',
  reasonRequiredMessage: 'Bitte einen Grund angeben.',
  confirmDeactivate: 'wird deaktiviert. Fiş/fatura referansları korunur; Konto kann später reaktiviert werden.',
  confirmReactivate: 'wieder aktivieren?',
  okDeactivate: 'Deaktivieren',
  okReactivate: 'Reaktivieren',
  close: 'Schließen',
  save: 'Speichern',
  cancel: 'Abbrechen',
  userName: 'Benutzername',
  password: 'Passwort',
  firstName: 'Vorname',
  lastName: 'Nachname',
  employeeNumber: 'Mitarbeiternummer',
  taxNumber: 'Steuernummer',
  notes: 'Notizen',
  activityTimeline: 'Aktivitätsverlauf',
  activityFor: 'Aktivitätsverlauf für',
  activityTime: 'Zeit',
  action: 'Aktion',
  description: 'Beschreibung',
  emptyList: 'Keine Benutzer gefunden.',
  emptyActivity: 'Keine Aktivität.',
  errorLoad: 'Benutzerliste konnte nicht geladen werden.',
  retry: 'Erneut versuchen',
  successCreate: 'Benutzer angelegt.',
  successUpdate: 'Benutzer aktualisiert.',
  successDeactivate: 'Benutzer deaktiviert.',
  successReactivate: 'Benutzer reaktiviert.',
  errorGeneric: 'Fehler.',
  noPermission: 'Nur Administratoren können Benutzer verwalten.',
  accessDenied: 'Sie haben keine Berechtigung, Benutzer anzuzeigen.',
  branchNotAvailable: '—',
  details: 'Details',
  resetPassword: 'Passwort zurücksetzen',
  resetPasswordUser: 'Passwort zurücksetzen',
  newPassword: 'Neues Passwort (min. 6 Zeichen)',
  successResetPassword: 'Passwort wurde zurückgesetzt. Sitzungen des Benutzers wurden ungültig.',
  successCreateRole: 'Rolle angelegt.',
  roleName: 'Rollenname',
  roleNameRequired: 'Rollenname erforderlich',
} as const;
